### ISSUE TITLE
sandbox running in Github Actions fails with `the input device is not a TTY`

### ISSUE THREAD

**Issue by jasonboukheir** [algorand/sandbox#64]
### Subject of the issue

I've tried setting it up sandbox as a service for my test workflow:
https://github.com/CareBoo/unity-algorand-sdk/blob/66efbd3c969242610fdb994095dd7eae0ecae9ff/.github/workflows/test.yaml

but I'm running into `the input device is not a TTY`

### Your environment

Github Action runner:
https://github.com/CareBoo/unity-algorand-sdk/blob/66efbd3c969242610fdb994095dd7eae0ecae9ff/.github/workflows/test.yaml

### Steps to reproduce

1. Create a ubuntu github workflow with the following steps:
```yaml
steps:
  - uses: actions/checkout@v2
    with:
      repository: algorand/sandbox
      path: sandbox
  - run: |
    cd sandbox
    ./sandbox up -v
```
2. Run the workflow

### Expected behaviour

the services should run successfully with an exit code of 0

### Actual behaviour

the services fail with `the input device is not a TTY` and exits 1
